from typing import Any, Dict


def default_operating_mirror_graph() -> Dict[str, Any]:
    return {
        "graph_id": "willow_operating_mirror_v1",
        "name": "Willow Operating Mirror",
        "domain": "chef_operations",
        "version": "1.0.0",
        "nodes": [
            {
                "id": "menu_complexity",
                "label": "Menu Complexity",
                "type": "operational_driver",
                "unit": "score_0_100",
                "current_value": 68,
                "confidence": 0.82,
                "description": "Measures prep difficulty and station burden.",
            },
            {
                "id": "prep_labor",
                "label": "Prep Labor",
                "type": "resource_load",
                "unit": "hours",
                "current_value": 42,
                "confidence": 0.78,
                "description": "Estimated prep labor hours.",
            },
            {
                "id": "team_stress",
                "label": "Team Stress",
                "type": "human_factor",
                "unit": "score_0_100",
                "current_value": 61,
                "confidence": 0.70,
                "description": "Estimated team strain from load and timing.",
            },
            {
                "id": "execution_risk",
                "label": "Execution Risk",
                "type": "risk",
                "unit": "score_0_100",
                "current_value": 57,
                "confidence": 0.76,
                "description": "Likelihood of service or operational issues.",
            },
            {
                "id": "client_experience",
                "label": "Client Experience",
                "type": "outcome",
                "unit": "score_0_100",
                "current_value": 84,
                "confidence": 0.74,
                "description": "Predicted client satisfaction.",
            },
            {
                "id": "repeat_bookings",
                "label": "Repeat Bookings",
                "type": "business_outcome",
                "unit": "probability",
                "current_value": 0.63,
                "confidence": 0.66,
                "description": "Probability of future client bookings.",
            },
            {
                "id": "ingredient_cost",
                "label": "Ingredient Cost",
                "type": "cost_driver",
                "unit": "usd",
                "current_value": 1850,
                "confidence": 0.86,
                "description": "Projected ingredient cost.",
            },
            {
                "id": "gross_margin",
                "label": "Gross Margin",
                "type": "financial_outcome",
                "unit": "percentage",
                "current_value": 0.41,
                "confidence": 0.80,
                "description": "Projected gross margin.",
            },
            {
                "id": "pricing_strategy",
                "label": "Pricing Strategy",
                "type": "decision",
                "unit": "score_0_100",
                "current_value": 72,
                "confidence": 0.73,
                "description": "Pricing quality versus complexity and value.",
            },
            {
                "id": "proposal_acceptance",
                "label": "Proposal Acceptance",
                "type": "sales_outcome",
                "unit": "probability",
                "current_value": 0.69,
                "confidence": 0.68,
                "description": "Probability that the proposal closes.",
            },
            {
                "id": "team_skill",
                "label": "Team Skill",
                "type": "capacity_driver",
                "unit": "score_0_100",
                "current_value": 79,
                "confidence": 0.77,
                "description": "Team capability across stations and service.",
            },
            {
                "id": "vendor_reliability",
                "label": "Vendor Reliability",
                "type": "supply_driver",
                "unit": "score_0_100",
                "current_value": 83,
                "confidence": 0.81,
                "description": "Likelihood of accurate, timely vendor delivery.",
            },
            {
                "id": "future_revenue",
                "label": "Future Revenue",
                "type": "business_outcome",
                "unit": "usd",
                "current_value": 12000,
                "confidence": 0.59,
                "description": "Projected downstream revenue.",
            },
            {
                "id": "brand_risk",
                "label": "Brand Risk",
                "type": "risk",
                "unit": "score_0_100",
                "current_value": 24,
                "confidence": 0.65,
                "description": "Risk of reputation damage from execution failure.",
            },
        ],
        "edges": [
            {
                "id": "menu_complexity_to_prep_labor",
                "source": "menu_complexity",
                "target": "prep_labor",
                "polarity": "positive",
                "weight": 0.74,
                "lag": "pre_event",
                "rationale": "More complexity drives prep hours.",
            },
            {
                "id": "prep_labor_to_team_stress",
                "source": "prep_labor",
                "target": "team_stress",
                "polarity": "positive",
                "weight": 0.63,
                "lag": "pre_event",
                "rationale": "Higher labor load increases stress.",
            },
            {
                "id": "team_stress_to_execution_risk",
                "source": "team_stress",
                "target": "execution_risk",
                "polarity": "positive",
                "weight": 0.58,
                "lag": "event_day",
                "rationale": "Stress raises execution failure risk.",
            },
            {
                "id": "execution_risk_to_client_experience",
                "source": "execution_risk",
                "target": "client_experience",
                "polarity": "negative",
                "weight": 0.69,
                "lag": "event_day",
                "rationale": "Higher risk can hurt client experience.",
            },
            {
                "id": "client_experience_to_repeat_bookings",
                "source": "client_experience",
                "target": "repeat_bookings",
                "polarity": "positive",
                "weight": 0.71,
                "lag": "post_event",
                "rationale": "Better experience drives repeat demand.",
            },
            {
                "id": "menu_complexity_to_ingredient_cost",
                "source": "menu_complexity",
                "target": "ingredient_cost",
                "polarity": "positive",
                "weight": 0.52,
                "lag": "proposal",
                "rationale": "Complex menus often increase cost.",
            },
            {
                "id": "ingredient_cost_to_gross_margin",
                "source": "ingredient_cost",
                "target": "gross_margin",
                "polarity": "negative",
                "weight": 0.78,
                "lag": "proposal",
                "rationale": "Higher cost can reduce margin.",
            },
            {
                "id": "pricing_strategy_to_gross_margin",
                "source": "pricing_strategy",
                "target": "gross_margin",
                "polarity": "positive",
                "weight": 0.81,
                "lag": "proposal",
                "rationale": "Better pricing improves margin.",
            },
            {
                "id": "pricing_strategy_to_proposal_acceptance",
                "source": "pricing_strategy",
                "target": "proposal_acceptance",
                "polarity": "mixed",
                "weight": 0.46,
                "lag": "proposal",
                "rationale": "Pricing influences acceptance with mixed effects.",
            },
            {
                "id": "team_skill_to_prep_labor",
                "source": "team_skill",
                "target": "prep_labor",
                "polarity": "negative",
                "weight": 0.49,
                "lag": "pre_event",
                "rationale": "Higher skill can reduce labor burden.",
            },
            {
                "id": "team_skill_to_execution_risk",
                "source": "team_skill",
                "target": "execution_risk",
                "polarity": "negative",
                "weight": 0.67,
                "lag": "event_day",
                "rationale": "Higher skill reduces execution risk.",
            },
            {
                "id": "vendor_reliability_to_ingredient_cost",
                "source": "vendor_reliability",
                "target": "ingredient_cost",
                "polarity": "negative",
                "weight": 0.38,
                "lag": "pre_event",
                "rationale": "Reliable vendors reduce emergency cost spikes.",
            },
            {
                "id": "vendor_reliability_to_execution_risk",
                "source": "vendor_reliability",
                "target": "execution_risk",
                "polarity": "negative",
                "weight": 0.54,
                "lag": "pre_event",
                "rationale": "Reliable supply lowers operational risk.",
            },
            {
                "id": "repeat_bookings_to_future_revenue",
                "source": "repeat_bookings",
                "target": "future_revenue",
                "polarity": "positive",
                "weight": 0.73,
                "lag": "future",
                "rationale": "Repeat demand increases future revenue.",
            },
            {
                "id": "gross_margin_to_future_revenue",
                "source": "gross_margin",
                "target": "future_revenue",
                "polarity": "positive",
                "weight": 0.57,
                "lag": "future",
                "rationale": "Higher retained margin supports future growth.",
            },
            {
                "id": "execution_risk_to_brand_risk",
                "source": "execution_risk",
                "target": "brand_risk",
                "polarity": "positive",
                "weight": 0.76,
                "lag": "post_event",
                "rationale": "Operational failures elevate brand risk.",
            },
        ],
        "metadata": {
            "created_by": "willow",
            "calibration_mode": "expert_seeded",
            "intended_use": [
                "event_planning",
                "menu_pricing",
                "post_event_analysis",
                "scenario_simulation",
                "executive_dashboard",
            ],
        },
    }
